### ISSUE TITLE
Graph data is showing multiple times

### ISSUE THREAD

**Issue by lsurasani** [HackGT/registration#127]
![screen shot 2017-09-09 at 5 35 46 pm](https://user-images.githubusercontent.com/16484180/30244126-dedc4e42-9585-11e7-9763-1b308abff654.png)

**Comment by petschekr** [comment]
This is happening due to an update to the way labels are rendered. Since labels are now rendered as Markdown, regular apostrophes (') are converted to curved apostrophes which is why they aren't aggregated entirely correctly with the old data. You won't see this issue on HackGTeeny or future deployments because those started accepting applications after this feature was added.

**Comment by petschekr** [comment]
Keeping this issue open because @ehsanmasdar and I might go back and manually update the old applications so that they get aggregated correctly

**Comment by petschekr** [comment]
Closing because this isn't relevant anymore
